# consts for pid optimisation

# Max pid section

MAX_KI = 5
MAX_KP = 5
MAX_KD = 5


# GA parameters section

POPULATION = 10
GENERATIONS = 100
SELECTION_RATE = 0.40
MUTATION_MULTIPLIER = 1.23
MAX_ADAPTIVENESS_CHANGE = 0.2
MUTATION_CONDITION = 0.09

# #Ratings
# ##KP
KP_STAT_ERR_ADAPTIVENESS_RATING = 4
KP_ABS_ERR_ADAPTIVENESS_RATING = 3
KP_OVER_ERR_ADAPTIVENESS_RATING = 2
KP_T5_ERR_ADAPTIVENESS_RATING = 1

# ##KI
KI_STAT_ERR_ADAPTIVENESS_RATING = 1
KI_ABS_ERR_ADAPTIVENESS_RATING = 4
KI_OVER_ERR_ADAPTIVENESS_RATING = 3
KI_T5_ERR_ADAPTIVENESS_RATING = 2

# ##KD
KD_STAT_ERR_ADAPTIVENESS_RATING = 1
KD_ABS_ERR_ADAPTIVENESS_RATING = 2
KD_OVER_ERR_ADAPTIVENESS_RATING = 4
KD_T5_ERR_ADAPTIVENESS_RATING = 3


# Sample analysis

MIN_POINTS_NUMBER = 200

# Comparison section

EPS = 0.0001
